version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.11
    steps:
      - checkout
      - run:
          name: Set up Python
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - run:
          name: Database Preparation
          command: |
            psql -c "DROP DATABASE IF EXISTS test_documentationocealia;"
            psql -c "CREATE DATABASE test_documentationocealia;"

      - run:
          name: Apply Migrations
          command: |
            python manage.py migrate

      - run:
          name: Run Tests
          command: |
            python manage.py test --keepdb
