version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
      - image: postgres:latest
        environment:
          POSTGRES_DB: documentationocealia
          POSTGRES_USER: gitadmin
          POSTGRES_PASSWORD: Ocealia31520
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Apply migrations to the test database
          command: python manage.py migrate --no-input
      - run:
          name: Run tests
          command: python manage.py test
      - run:
          name: Check if auth_user table exists
          command: |
            python manage.py dbshell -c "SELECT * FROM auth_user LIMIT 1;"