version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11  # Nouvelle image officielle
      - image: postgres:latest
        environment:
          POSTGRES_DB: documentationocealia
          POSTGRES_USER: gitadmin
          POSTGRES_PASSWORD: Ocealia31520
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Apply migrations
          command: python manage.py migrate
      - run:
          name: Reset test database
          command: python manage.py test --keepdb
      - run:
          name: Check database tables
          command: |
            echo "from django.db import connection; print(connection.introspection.table_names())" | python manage.py shell
      - run:
          name: Run tests
          command: python manage.py test

workflows:
  version: 2
  test:
    jobs:
      - test
