# Generated by Django 5.2.4 on 2025-07-29 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnalite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('id_fonctionnalite', models.CharField(default=0, max_length=10, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gamme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InterfaceUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('is_master', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dtd', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('fonctionnalites', models.ManyToManyField(related_name='audiences', to='documentation.fonctionnalite')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('abreviation', models.CharField(max_length=5)),
                ('is_archived', models.BooleanField(default=False)),
                ('gamme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='documentation.gamme')),
            ],
        ),
        migrations.AddField(
            model_name='fonctionnalite',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fonctionnalites', to='documentation.produit'),
        ),
        migrations.CreateModel(
            name='ProfilPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_sortie', models.CharField(choices=[('PDF', 'PDF'), ('Web', 'Web Help'), ('Moodle', 'Moodle'), ('Fiche', 'Fiche Pratique')], max_length=50)),
                ('parametres', models.JSONField(default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='documentation.map')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('version_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('date_lancement', models.DateTimeField(blank=True, null=True)),
                ('notes_version', models.TextField(blank=True, null=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gamme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation.gamme')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='documentation.projet'),
        ),
        migrations.CreateModel(
            name='Rubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu_xml', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateField(auto_now=True)),
                ('audience', models.CharField(default='générique', max_length=200)),
                ('revision_numero', models.IntegerField()),
                ('version', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fonctionnalite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation.fonctionnalite')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_rubriques', to=settings.AUTH_USER_MODEL)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.projet')),
                ('version_precedente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentation.rubrique')),
                ('type_rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.typerubrique')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_media', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=50)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('chemin_acces', models.TextField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='documentation.produit')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='documentation.rubrique')),
            ],
            options={
                'db_table': 'media',
            },
        ),
        migrations.CreateModel(
            name='MapRubrique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.map')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enfants', to='documentation.maprubrique')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.rubrique')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.AddField(
            model_name='map',
            name='rubriques',
            field=models.ManyToManyField(related_name='maps', through='documentation.MapRubrique', to='documentation.rubrique'),
        ),
        migrations.CreateModel(
            name='LogModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=100)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='documentation.projet')),
                ('rubrique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='documentation.rubrique')),
            ],
        ),
        migrations.CreateModel(
            name='VersionProjet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_numero', models.CharField(max_length=50)),
                ('date_lancement', models.DateTimeField(blank=True, null=True)),
                ('notes_version', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documentation.projet')),
            ],
        ),
        migrations.AddField(
            model_name='rubrique',
            name='version_projet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rubriques', to='documentation.versionprojet'),
        ),
        migrations.AlterUniqueTogether(
            name='fonctionnalite',
            unique_together={('produit', 'code')},
        ),
    ]
