# Generated by Django 5.2.4 on 2025-07-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='abreviation',
            field=models.CharField(max_length=4),
        ),
    ]
