# Generated by Django 5.2.4 on 2025-08-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_alter_fonctionnalite_id_fonctionnalite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonctionnalite',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='fonctionnalite',
            name='id_fonctionnalite',
            field=models.CharField(default='0000', max_length=8, unique=True),
        ),
    ]
