# Generated by Django 5.2.4 on 2025-08-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0004_alter_fonctionnalite_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="rubrique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medias",
                to="documentation.rubrique",
            ),
        ),
    ]
