# Generated by Django 5.2.4 on 2025-12-13 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0005_alter_media_rubrique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubrique",
            name="type_rubrique",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="documentation.typerubrique",
            ),
        ),
    ]
