# Generated by Django 5.2.4 on 2025-12-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0007_alter_rubrique_revision_numero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubrique",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
