# Generated by Django 5.2.4 — Chantier 6 Versioning documentaire (Lot 1)
# Migration additive uniquement : aucune modification de table existante.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0008_alter_rubrique_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- RevisionRubrique ---
        migrations.CreateModel(
            name="RevisionRubrique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.PositiveIntegerField()),
                ("contenu_xml", models.TextField()),
                ("hash_contenu", models.CharField(max_length=64)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revisions_rubriques",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rubrique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="documentation.rubrique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Révision de rubrique",
                "verbose_name_plural": "Révisions de rubrique",
                "ordering": ["rubrique", "numero"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="revisionrubrique",
            unique_together={("rubrique", "numero")},
        ),
        # --- SnapshotPublication ---
        migrations.CreateModel(
            name="SnapshotPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="documentation.versionprojet",
                    ),
                ),
                (
                    "rubrique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots_publication",
                        to="documentation.rubrique",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="documentation.revisionrubrique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de publication",
                "verbose_name_plural": "Snapshots de publication",
            },
        ),
        migrations.AlterUniqueTogether(
            name="snapshotpublication",
            unique_together={("version_projet", "rubrique")},
        ),
    ]
