# Generated by Django 5.2.4 on 2025-07-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0002_alter_produit_abreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fonctionnalite',
            name='id_fonctionnalite',
            field=models.CharField(default=0, max_length=8, unique=True),
        ),
    ]
