# Generated by Django 5.2.4 on 2025-12-13 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0006_alter_rubrique_type_rubrique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rubrique",
            name="revision_numero",
            field=models.IntegerField(default=1),
        ),
    ]
