# Generated by Django 5.2.4 — Chantier 6 Versioning documentaire (Lot 1)
# Migration de données uniquement : pas de modification de schéma.
#
# Hypothèses de backfill :
# - Chaque Rubrique existante reçoit une RevisionRubrique(numero=1).
# - contenu_xml et hash_contenu sont calculés depuis Rubrique.contenu_xml courant.
# - auteur_id est repris depuis Rubrique.auteur_id (peut être null).
# - Les rubriques avec contenu_xml vide (racines documentaires) reçoivent
#   une révision avec hash de chaîne vide — valide et cohérent.
# - XML invalide : on hash le texte brut strippé sans bloquer (défense en profondeur).
# - Exécution en bulk_create pour les performances sur large volume.
#
# Reverse : noop — on ne peut pas supprimer proprement les révisions backfillées
# sans risquer de supprimer des révisions créées après coup.

import hashlib
import xml.etree.ElementTree as ET

from django.db import migrations


# --- Hash inline (ne pas importer depuis utils pour l'isolation des migrations) ---

def _compute_xml_hash(xml_str):
    """Identique à utils.compute_xml_hash — inline pour isolation de migration."""
    stripped = (xml_str or "").strip()
    if not stripped:
        return hashlib.sha256(b"").hexdigest()
    try:
        root = ET.fromstring(stripped)
        normalized = ET.tostring(root, encoding="unicode")
    except ET.ParseError:
        normalized = stripped
    return hashlib.sha256(normalized.encode("utf-8")).hexdigest()


def backfill_revisions_initiales(apps, schema_editor):
    """
    Crée une RevisionRubrique(numero=1) pour chaque Rubrique existante
    qui n'en possède pas encore.

    La vérification d'existence permet de rejouer la migration sans doublon
    si elle est interrompue et relancée partiellement.
    """
    Rubrique = apps.get_model("documentation", "Rubrique")
    RevisionRubrique = apps.get_model("documentation", "RevisionRubrique")

    # Rubriques déjà couvertes (sécurité idempotence)
    deja_couverts = set(
        RevisionRubrique.objects.filter(numero=1).values_list("rubrique_id", flat=True)
    )

    revisions = []
    for rubrique in Rubrique.objects.all().iterator():
        if rubrique.pk in deja_couverts:
            continue
        revisions.append(
            RevisionRubrique(
                rubrique_id=rubrique.pk,
                numero=1,
                contenu_xml=rubrique.contenu_xml or "",
                hash_contenu=_compute_xml_hash(rubrique.contenu_xml),
                auteur_id=rubrique.auteur_id,
                # date_creation sera auto_now_add — date de migration, acceptable
            )
        )

    if revisions:
        RevisionRubrique.objects.bulk_create(revisions)


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0009_add_versioning_tables"),
    ]

    operations = [
        migrations.RunPython(
            backfill_revisions_initiales,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
