# Generated by Django 5.2.4 — Chantier 6 Versioning documentaire
# Renommage SnapshotPublication → PublicationSnapshot sur demande MOA.
# Renomme la table DB : documentation_snapshotpublication → documentation_publicationsnapshot.
# Les related_names sont mis à jour dans le code (Python only, sans migration).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0010_backfill_revision_initiale"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SnapshotPublication",
            new_name="PublicationSnapshot",
        ),
    ]
