# Generated by Django 5.2.4 on 2026-04-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0011_rename_snapshotpublication_publicationsnapshot"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicationsnapshot",
            options={
                "verbose_name": "Publication Snapshot",
                "verbose_name_plural": "Publication Snapshots",
            },
        ),
        migrations.AlterField(
            model_name="publicationsnapshot",
            name="revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_snapshots",
                to="documentation.revisionrubrique",
            ),
        ),
        migrations.AlterField(
            model_name="publicationsnapshot",
            name="rubrique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_snapshots",
                to="documentation.rubrique",
            ),
        ),
        migrations.AlterField(
            model_name="publicationsnapshot",
            name="version_projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publication_snapshots",
                to="documentation.versionprojet",
            ),
        ),
        migrations.CreateModel(
            name="VersionProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_preparation", "En préparation"),
                            ("publiee", "Publiée"),
                            ("archivee", "Archivée"),
                        ],
                        default="en_preparation",
                        max_length=20,
                    ),
                ),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="documentation.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version Produit",
                "verbose_name_plural": "Versions Produit",
                "unique_together": {("produit", "numero")},
            },
        ),
        migrations.CreateModel(
            name="EvolutionProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("evolution", "Évolution"),
                            ("correctif", "Correctif"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("ordre", models.PositiveIntegerField(default=0)),
                (
                    "statut",
                    models.CharField(
                        choices=[("draft", "Brouillon"), ("valide", "Validé")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_archived", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fonctionnalite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="evolutions",
                        to="documentation.fonctionnalite",
                    ),
                ),
                (
                    "version_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evolutions",
                        to="documentation.versionproduit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Évolution Produit",
                "verbose_name_plural": "Évolutions Produit",
                "ordering": ["ordre"],
            },
        ),
    ]
