# Generated by Django 5.2.4 on 2026-04-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0012_versionproduit_evolutionproduit"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImpactDocumentaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("a_faire", "À faire"),
                            ("en_cours", "En cours"),
                            ("pret", "Prêt"),
                            ("valide", "Validé"),
                            ("ignore", "Ignoré"),
                        ],
                        default="a_faire",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "evolution_produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impacts",
                        to="documentation.evolutionproduit",
                    ),
                ),
                (
                    "rubrique",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="impacts_produit",
                        to="documentation.rubrique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Impact Documentaire",
                "verbose_name_plural": "Impacts Documentaires",
                "unique_together": {("evolution_produit", "rubrique")},
            },
        ),
    ]
