# Generated by Django 5.2.4 on 2026-04-18 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0013_impactdocumentaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactdocumentaire",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
