#test
name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_documentationocealia
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: Ocealia31520
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U admin -d test_documentationocealia"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB: test_documentationocealia
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Ocealia31520
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

     steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Show directory structure
      run: |
        echo "Working Directory: $(pwd)"
        ls -R

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dj-database-url
      run: |
        pip install dj-database-url
        pip show dj-database-url

    - name: List Installed Packages
      run: pip list

    - name: Install dependencies
      run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt
       pip install dj-database-url

    - name: Navigate to project directory
      run: cd documentation.project

    - name: Create logs directory
      run: mkdir -p documentation.project/logs

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: python manage.py test