name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: documentationocealia
          POSTGRES_USER: gitadmin
          POSTGRES_PASSWORD: Ocealia31520
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U gitadmin -d documentationocealia"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      POSTGRES_DB: documentationocealia
      POSTGRES_USER: gitadmin
      POSTGRES_PASSWORD: Ocealia31520
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create logs directory
      run: mkdir -p documentation.project/logs

    - name: Apply migrations
      run: python manage.py migrate

    - name: Reset test database
      run: python manage.py test --keepdb
      
    - name: Check database tables
      run: |
       echo "from django.db import connection; print(connection.introspection.table_names())" | python manage.py shell

    - name: Run tests
      run: python manage.py test
